// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// SearchAlgorithmUsecase is an autogenerated mock type for the SearchAlgorithmUsecase type
type SearchAlgorithmUsecase struct {
	mock.Mock
}

// Search provides a mock function with given fields: keyword
func (_m *SearchAlgorithmUsecase) Search(keyword string) (int, error) {
	ret := _m.Called(keyword)

	var r0 int
	if rf, ok := ret.Get(0).(func(string) int); ok {
		r0 = rf(keyword)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(keyword)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewSearchAlgorithmUsecase interface {
	mock.TestingT
	Cleanup(func())
}

// NewSearchAlgorithmUsecase creates a new instance of SearchAlgorithmUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSearchAlgorithmUsecase(t mockConstructorTestingTNewSearchAlgorithmUsecase) *SearchAlgorithmUsecase {
	mock := &SearchAlgorithmUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
